db:
  # MySQL config
  type: mysql
  dns: root:ding@tcp(localhost:3306)/dev?charset=utf8&parseTime=True&loc=Local

  # Postgres config
  # type: postgres
  # dns: host=localhost port=5432 user=postgres password=ding dbname=dev sslmode=disable TimeZone=Asia/Shanghai

  # SQLServer config
  # type: sqlserver
  # dns: sqlserver://sa:Ding@1234@localhost:1433?database=dev

  # SQLite config
  # type: sqlite
  # dns: file:/Users/dp/.dev/data/dev.db?cache=shared&mode=rwc